schema:
	xmllint --noout --schema ../schema.xsd cmlDict.xml
	xmllint --noout --schema ../schema.xsd jcampDict.xml
	xmllint --noout --schema ../schema.xsd nmrDict.xml
	xmllint --noout --schema ../schema.xsd siUnitsDict.xml
	xmllint --noout --schema ../schema.xsd substDict.xml
	xmllint --noout --schema ../schema.xsd unitsDict.xml
