schema:
	xmllint --noout --schema schema.xsd example0.xml
	xmllint --noout --schema schema.xsd example1.xml
	xmllint --noout --schema schema.xsd example2.xml
	xmllint --noout --schema schema.xsd example3.xml
	xmllint --noout --schema schema.xsd example4.xml

schematron:
	xmllint --noout --schematron nmrshiftdb-convention.schematron example1.xml
